<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[==== Db Connection Established successfully===]]>
    </line>
    <line>
      <![CDATA[==Broswer Launch ==]]>
    </line>
    <line>
      <![CDATA[====Login to Application Successfully == ]]>
    </line>
    <line>
      <![CDATA[=== Click On Organization Link ===]]>
    </line>
    <line>
      <![CDATA[=== Click create On Organization Link ===]]>
    </line>
    <line>
      <![CDATA[createContactWithExisOrg The Test Script execution failed]]>
    </line>
  </reporter-output>
  <suite started-at="2022-03-16T17:03:00 IST" name="Default suite" finished-at="2022-03-16T17:07:48 IST" duration-ms="288763">
    <groups>
    </groups>
    <test started-at="2022-03-16T17:03:00 IST" name="Default test" finished-at="2022-03-16T17:07:48 IST" duration-ms="288763">
      <class name="com.crm.ContactsTests.CreateContactWithExistingOrgztn">
        <test-method is-config="true" signature="ConnectDataBase()[pri:0, instance:com.crm.ContactsTests.CreateContactWithExistingOrgztn@611889f4]" started-at="2022-03-16T17:03:00 IST" name="ConnectDataBase" finished-at="2022-03-16T17:03:00 IST" duration-ms="14" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[==== Db Connection Established successfully===]]>
            </line>
          </reporter-output>
        </test-method> <!-- ConnectDataBase -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:com.crm.ContactsTests.CreateContactWithExistingOrgztn@611889f4]" started-at="2022-03-16T17:03:02 IST" name="launchBrowser" finished-at="2022-03-16T17:04:02 IST" duration-ms="60573" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[==Broswer Launch ==]]>
            </line>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method is-config="true" signature="logintoApp()[pri:0, instance:com.crm.ContactsTests.CreateContactWithExistingOrgztn@611889f4]" started-at="2022-03-16T17:04:03 IST" name="logintoApp" finished-at="2022-03-16T17:06:39 IST" duration-ms="156937" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[====Login to Application Successfully == ]]>
            </line>
          </reporter-output>
        </test-method> <!-- logintoApp -->
        <test-method signature="createContactWithExisOrg()[pri:0, instance:com.crm.ContactsTests.CreateContactWithExistingOrgztn@611889f4]" started-at="2022-03-16T17:06:39 IST" name="createContactWithExisOrg" finished-at="2022-03-16T17:07:47 IST" duration-ms="67732" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.ContactsTests.CreateContactWithExistingOrgztn.createContactWithExisOrg(CreateContactWithExistingOrgztn.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[=== Click On Organization Link ===]]>
            </line>
            <line>
              <![CDATA[=== Click create On Organization Link ===]]>
            </line>
            <line>
              <![CDATA[createContactWithExisOrg The Test Script execution failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- createContactWithExisOrg -->
      </class> <!-- com.crm.ContactsTests.CreateContactWithExistingOrgztn -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
